@echo off
rem Generated by JetBrains Toolbox 2.2.3.20090 at 2024-03-13T15:36:53.681825400

set waitarg=
set intellij_args=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "intellij_args=%intellij_args%--wait ") else (set "intellij_args=%intellij_args%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\eau\AppData\Local\Programs\CLion\bin\clion64.exe %intellij_args%