@echo off
rem Generated by JetBrains Toolbox 1.25.12569 at 2022-07-27T15:52:24.769124

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\emory.au\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\221.5080.212\bin\pycharm64.exe %ideargs%