@echo off
rem Generated by JetBrains Toolbox 1.20.7940 at 2021-02-24T18:09:23.591770700

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\emory.au\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\203.7148.54\bin\webstorm64.exe %ideargs%